/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_authentification (void);
GtkWidget* create_window_ADMIN (void);
GtkWidget* create_window_claim (void);
GtkWidget* create_window_electorallist (void);
GtkWidget* create_window_statsoum (void);
GtkWidget* create_window_signinadmin (void);
GtkWidget* create_window_signinactor (void);
